default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projeto_academia_development

test:
  <<: *default
  database: projeto_academia_test

production:
  primary: &primary_production
    <<: *default
    database: projeto_academia_production
    username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  cache:
    <<: *primary_production
    database: projeto_academia_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: projeto_academia_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: projeto_academia_production_cable
    migrations_paths: db/cable_migrate